# Generated by Django 5.0.7 on 2026-02-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_branch_appointment_branch_clinic_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.branch'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('phone_number', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('phone_number', 'branch')},
        ),
    ]
