# Generated by Django 5.0.7 on 2026-05-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_doctorschedule_branch_alter_doctor_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
    ]
