# Generated by ChatGPT on 2026-05-05
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_patient_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("total_revenue", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("total_patients", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="app.branch")),
            ],
            options={
                "unique_together": {("branch", "date")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("total_revenue", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("total_patients", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="app.branch")),
                ("clinic", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="app.clinic")),
                ("doctor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="app.doctor")),
            ],
            options={
                "unique_together": {("branch", "doctor", "clinic", "date", "start_time", "end_time")},
            },
        ),
    ]
