# Generated by Django 5.0.7 on 2026-06-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_printjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='ticket_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
