# Generated by Django 5.0.7 on 2026-06-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_appointment_ticket_number'),
        ('app', '0012_printjob_ticket_number'),
    ]

    operations = [
    ]
